### ISSUE TITLE
Epub: Opening and ending tag mismatch errors

### ISSUE THREAD

**Issue by drevansa** [ColauttiLab/RCrashCourse_Book#1]
Viewing EPub version of RCrahsCourse_Book on Mac Books eReader, errors:
P1 ln 26, column 60, opening and ending tag mismatch: br line 0 and h1
p2 ln 26, column 63, opening and ending tag mismatch: br line 0 and h1
p21 ln 160, column 12, opening and ending tag mismatch: br line 0 p
p23 ln 206, column 12, opening and ending tag mismatch: br line 0 p
p27 ln 262, column 12, opening and ending tag mismatch: br line 0 p
p39 ln 167, column 12, opening and ending tag mismatch: br line 0 p

Example:
<img width="1011" alt="Screenshot 2022-12-03 at 20 59 38" src="https://user-images.githubusercontent.com/12700047/205462308-393ec50c-33d6-4096-be3d-a6fcb703944e.png">

**Comment by ColauttiLab** [comment]
fixed for the second edition, release in Feb/March 2024
